server:
  port: 8084

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gestion_dons1
    username: postgres
    password: sofia@2019
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect



